# Generated by Django 2.2.13 on 2020-06-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_pet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
